function [agents, params] = scn_ui_custom(params)
% Auto-generated by ScenarioBuilderV1_1 on 17-Nov-2025 17:45:53
% This scenario contains 2 agents

agents = [];

% Agent 1 (VO)
a = Agent(1,[0.000000 -14.000000],[0.000000 14.000000],0.500000,1.000000,'VO',[0.000000 0.000000]);
a.safetyRadius = 1.000000;
a.color = [0.934 0.187 0.266];
agents = [agents, a];

% Agent 2 (VO)
a = Agent(2,[1.000000 14.000000],[1.000000 -14.000000],0.500000,1.000000,'VO',[0.000000 0.000000]);
a.safetyRadius = 1.000000;
a.color = [0.396 0.273 0.037];
agents = [agents, a];

% Update parameters if needed (几何 / 仿真相关，避碰静态参数仍由配置类控制)
params.world.fieldSize = 20.000000;
params.sim.dt = 0.050000;
params.sim.maxSteps = 700;
% ds_base / dp_factor / timeHorizon / perceptionDist / neighborDist
% 请在 SimConfigV1_1.default() 中统一配置。

end
