function [agents, params] = scn_ui_customhead3(params)
% Auto-generated by ScenarioBuilderV1_1 on 16-Nov-2025 22:08:55
% This scenario contains 2 agents

agents = [];

% Agent 5 (VO)
a = Agent(5,[0.000000 -15.000000],[0.000000 17.000000],0.300000,1.000000,'VO',[0.000000 0.000000]);
a.safetyRadius = 1.000000;
a.color = [0.790 0.319 0.534];
agents = [agents, a];

% Agent 3 (CONST)
a = Agent(3,[0.000000 15.000000],[-0.121655 -14.063260],0.300000,1.200000,'CONST',[1.200000 0.000000]);
a.safetyRadius = 1.000000;
a.color = [0.550 0.550 0.550];
a.setWaypoints([0.000000 15.000000; -0.121655 -14.063260], 'none', 1.200000, 0.300000);
agents = [agents, a];

% Update parameters if needed (几何 / 仿真相关，避碰静态参数仍由配置类控制)
params.world.fieldSize = 20.000000;
params.sim.dt = 0.050000;
params.sim.maxSteps = 3000;
% ds_base / dp_factor / timeHorizon / perceptionDist / neighborDist
% 请在 SimConfigV1_1.default() 中统一配置。

end
